---

- name: Install prereqs
  apt: name={{ item }}
  with_items:
    - supervisor
    - pandoc

- name: create skier install and config dirs
  file: dest={{ item }} state=directory
  with_items:
    - "{{ skier_install_dir }}"
    - "{{ skier_config_dir }}"

- name: create skier log dir
  file: dest={{ skier_log_dir }} state=directory owner={{ skier_proc_user }}

- name: clone skier
  git:
    repo=https://github.com/SkierPGP/Skier.git
    dest={{ skier_install_dir }}
    version={{ skier_version }}

- name: Create skier virtualenv + dependencies
  pip:
    virtualenv={{ skier_venv_dir }}
    requirements={{ skier_install_dir }}/requirements.txt
    virtualenv_python={{ python3_version }}

- name: Install psycopg2
  pip: name=psycopg2

- name: Create postgres db user for skier
  postgresql_user:
    name=skier
    password={{ skier_user_password }}

- name: Create postgres db for skier
  postgresql_db: name=skier owner=skier

# This echo bit is to get around a bug in ansibles yaml parsing
- name: Generate db schema
  shell:
    echo ''; {{ skier_venv_dir }}/bin/python3.4 {{ skier_install_dir }}/manager.py db upgrade
    chdir={{ skier_install_dir }}

- name: grant privileges to skier
  postgresql_privs: db=skier roles=skier privs=ALL type=database

- name: Generate autotemplates
  shell: su root -c 'source {{ skier_venv_dir }}/bin/activate; /bin/bash {{ skier_install_dir }}/setup.sh {{ skier_install_dir }}' chdir={{ skier_install_dir }}

- name: Generate gunicorn config
  template: src=skier_gunicorn_config.py dest={{ skier_config_dir }}/gunicorn_config.py
  notify:
    - restart skier

- name: Generate skier supervisor config
  template: src=skier_supervisor.conf dest={{ meg_supervisor_config_dir }}/skier.conf
  notify:
    - restart skier

- name: register supervisor app
  supervisorctl: name=skier state=present

- name: push skier nginx config
  template: src=skier_nginx dest=/etc/nginx/sites-available/skier
  notify:
    - reload nginx

- name: enable skier
  file: src=/etc/nginx/sites-available/skier dest=/etc/nginx/sites-enabled/skier state=link
  notify:
    - reload nginx
