---

- name: reload nginx
  service: name=nginx state=reloaded

- name: restart skier
  supervisorctl: name=skier state=restarted

- name: restart megserver
  supervisorctl: name=megserver state=restarted
