db:
  host: localhost
  port: 5432
  user: meg
  password: {{ meg_user_password }}
  database: meg

gcm_api_key: {{ megserver_gcm_api_key }}

meg_url_prefix: {{ megserver_nginx_location }}

keyservers:
  - http://localhost/skier
